# Generated by Django 4.2.11 on 2024-04-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='priority',
        ),
    ]
