# Generated by Django 4.2.11 on 2024-04-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_remove_bugreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
