# Generated by Django 4.2.11 on 2024-04-20 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_bugreport_priority_alter_featurerequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
